name: first workflow

on: push

jobs:
    job1:
        name: First job
        runs-on: ubuntu-latest
        steps:
            - name: Step one job1
              uses: actions/checkout@v2
            - name: Step two job1
              run: env | sort
    job2:
        name: Second job
        runs-on: windows-latest
        steps:
            - name: Step one job2
              uses: actions/checkout@v2
            - name: Step two job2
              run: "Get-ChildItem Env: | Sort-Object Name"